# Generated by Django 4.0.5 on 2022-06-08 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=200, verbose_name='назва категорії')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='посилання')),
            ],
            options={
                'verbose_name': 'категорія',
                'verbose_name_plural': 'категорії',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_category_name', models.CharField(db_index=True, max_length=200, verbose_name='дочірня категорія')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='посилання')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_category', to='shop.category', verbose_name='категорія')),
            ],
            options={
                'verbose_name': 'дочірня категорія',
                'verbose_name_plural': 'дочірні категорії',
                'ordering': ('child_category_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=200, verbose_name='назва товару')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='посилання')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='зображення')),
                ('description', models.TextField(blank=True, verbose_name='опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ціна')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, verbose_name='кількість')),
                ('available', models.BooleanField(default=True, verbose_name='доступний')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='оновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
                ('child_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.childcategory')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товари',
                'ordering': ('-created',),
            },
        ),
    ]
